name: 'Test'
on: [pull_request, push]

jobs:
  release:
    runs-on: ${{ matrix.platform }}
    name: Release

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-12
          - macos-14
          - windows-2019
          - windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: npm install

    - name: Test
      run: npm test


  debug:
    runs-on: ubuntu-latest
    name: Debug

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        npm install
        npx xpm run clean
        npx xpm run prepare --config debug
        npx xpm run build

    - name: Test
      run: npm test


  asan:
    runs-on: ubuntu-22.04
    name: Address Sanitization

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Build
      run: |
        npm install
        rm -rf build
        npx xpm run prepare --config debug
        npx xpm run configure -- -Db_sanitize=address
        npx xpm run build

    - name: Test
      run: npm test
      env:
        LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libasan.so.6
        LSAN_OPTIONS: suppressions=${{ github.workspace }}/test/napi-leaks-suppression.txt


  codecov:
    runs-on: ubuntu-22.04
    name: Code Coverage

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        npm install
        rm -rf build
        npx xpm run prepare --config debug
        npx xpm run configure -- -Db_coverage=true -Dbuildtype=debugoptimized '-Dcpp_args="--coverage -ftest-coverage"'
        npx xpm run build

    - name: Test
      run: |
        npx c8 npm test
        npm run gcov
        npm run lcov
 
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: coverage
        slug: mmomtchev/hadron-nobind-example-project
